"""Port interfaces (protocols) for dependency inversion.

All infrastructure must implement these protocols.
Services depend ONLY on these — never on concrete implementations.
"""

from __future__ import annotations

from typing import Protocol

import numpy as np

from app.domain.models import ClassNode, FunctionNode, ImportNode, Memory


class GraphStorePort(Protocol):
    def add_function(self, func: FunctionNode) -> None: ...
    def add_class(self, cls: ClassNode) -> None: ...
    def add_import(self, imp: ImportNode) -> None: ...
    def add_call_edge(self, project_id: str, caller_id: str, callee_id: str) -> None: ...
    def get_function(self, project_id: str, function_id: str) -> dict | None: ...
    def get_callees(self, project_id: str, function_id: str) -> list[dict]: ...
    def get_callers(self, project_id: str, function_id: str) -> list[dict]: ...
    def get_call_graph(self, project_id: str, function_id: str, depth: int = 2) -> dict: ...
    def get_all_functions(self, project_id: str) -> list[dict]: ...
    def remove_file_nodes(self, project_id: str, file_path: str) -> None: ...
    def clear_project(self, project_id: str) -> None: ...
    def save(self, project_id: str) -> None: ...


class VectorStorePort(Protocol):
    def add(self, project_id: str, node_id: str, embedding: np.ndarray, metadata: dict | None = None) -> None: ...
    def add_batch(self, project_id: str, node_ids: list[str], embeddings: np.ndarray, metadata_list: list[dict]) -> None: ...
    def search(self, project_id: str, query_embedding: np.ndarray, top_k: int = 10) -> list[dict]: ...
    def remove_by_file(self, project_id: str, file_path: str) -> None: ...
    def clear_project(self, project_id: str) -> None: ...
    def save(self, project_id: str) -> None: ...


class MemoryStorePort(Protocol):
    def add(self, memory: Memory) -> Memory: ...
    def get(self, memory_id: str) -> Memory | None: ...
    def search(self, project_id: str, query: str = "", type_filter: str = "", limit: int = 20) -> list[Memory]: ...
    def delete(self, memory_id: str) -> bool: ...


class EmbeddingPort(Protocol):
    @property
    def dimension(self) -> int: ...
    def generate(self, text: str) -> np.ndarray: ...
    def generate_batch(self, texts: list[str]) -> np.ndarray: ...


class CachePort(Protocol):
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    def delete(self, key: str) -> None: ...
    def clear(self) -> None: ...
